stages:
  - build

variables:
  FRONTEND_IMAGE: FRONTEND-$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  ORCHASTRATOR_IMAGE: ORCHASTRATOR_IMAGE-$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  MOCK_ML_IMAGE: MOCK_ML_IMAGE-$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

build:
  stage: build
  script:
    - docker login -u lukeconnolly2 -p $DOCKER_TOKEN
    - docker build -t $FRONTEND_IMAGE ./frontend
    - docker push $FRONTEND_IMAGE
    - docker build -t $ORCHASTRATOR_IMAGE ./orchestrator
    - docker push $ORCHASTRATOR_IMAGE
    - docker build -t $MOCK_ML_IMAGE ./mock-ml
    - docker push $MOCK_ML_IMAGE