version: '3'
services: 
  frontend:
    build: 
      context: ./frontend
    ports:
      - "3000:3000"

    depends_on:
      - orchastrator
      - db
    
  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: fyp-db  
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    
  orchastrator:
    build: 
      context: ./orchastrator
    ports:
      - "8080:8080"
    depends_on:
      - db
  
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: luke
      MINIO_ROOT_PASSWORD: lukelukeluke
    command: server --console-address ":9001" /data

volumes:
  minio_storage: {}
    