apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: andreasxou/hitl-frontend:v1
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
            - name: CLERK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: CLERK_SECRET_KEY
            - name: NEXT_PUBLIC_CLERK_SIGN_IN_URL
              valueFrom:
                configMapKeyRef:
                  name: fyp-config
                  key: NEXT_PUBLIC_CLERK_SIGN_IN_URL
            - name: NEXT_PUBLIC_CLERK_SIGN_UP_URL
              valueFrom:
                configMapKeyRef:
                  name: fyp-config
                  key: NEXT_PUBLIC_CLERK_SIGN_UP_URL
            - name: NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
              valueFrom:
                configMapKeyRef:
                  name: fyp-config
                  key: NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
            - name: NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
              valueFrom:
                configMapKeyRef:
                  name: fyp-config
                  key: NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
            - name: PRIVATE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: PRIVATE_API_KEY
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: fyp-config
                  key: DATABASE_URL
            - name: ORCHESTRATOR_URL
              valueFrom:
                configMapKeyRef:
                  name: fyp-config
                  key: ORCHESTRATOR_URL
            - name: RESEND_API_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: RESEND_API_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP # Changed from NodePort to ClusterIP
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
