apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: daisthree.ucd.ie #Your domain
      http:
        paths:
          - path: /results
            pathType: Prefix
            backend:
              service:
                name: orchestrator
                port:
                  number: 80
 
          - path: /getUploadURL
            pathType: Prefix
            backend:
              service:
                name: orchestrator
                port:
                  number: 80
          - path: /video
            pathType: Prefix
            backend:
              service:
                name: orchestrator
                port:
                  number: 80
                    
          # Default catch-all route for frontend service
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000
