apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
spec:
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
        - name: orchestrator
          image: andreasxou/hitl-backend:v1.1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          env:
            - name: DATALAKE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DATALAKE_CONNECTION_STRING
            - name: PRIVATE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: PRIVATE_API_KEY
            - name: PUBLIC_DATALAKE_URL
              valueFrom:
                configMapKeyRef:
                  name: fyp-config
                  key: PUBLIC_DATALAKE_URL
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: MONGO_USER
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: MONGO_PASS
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: fyp-config
                  key: DATABASE_URL
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: fyp-config
                  key: DATABASE_PORT

---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator
spec:
  type: ClusterIP
  selector:
    app: orchestrator
  ports:
    - port: 80
      targetPort: 80
