import { Video } from "@/types/video"

export const testVideos: Video[] = [
  {
    _id: "1",
    views: 100,
    status: "Success",
    requiredViews: 1000,
    public_url: "http://example.com/1",
    user: "User1",
  },
  {
    _id: "2",
    views: 200,
    status: "Failed",
    requiredViews: 2000,
    public_url: "http://example.com/2",
    user: "User2",
  },
  {
    _id: "3",
    views: 300,
    status: "Unreleased",
    requiredViews: 3000,
    public_url: "http://example.com/3",
    user: "User3",
  },
  {
    _id: "4",
    views: 400,
    status: "Collecting preferences",
    requiredViews: 4000,
    public_url: "http://example.com/4",
    user: "User4",
  },
  {
    _id: "5",
    views: 500,
    status: "Success",
    requiredViews: 5000,
    public_url: "http://example.com/5",
    user: "User5",
  },
  {
    _id: "6",
    views: 600,
    status: "Failed",
    requiredViews: 6000,
    public_url: "http://example.com/6",
    user: "User6",
  },
  {
    _id: "7",
    views: 700,
    status: "Unreleased",
    requiredViews: 7000,
    public_url: "http://example.com/7",
    user: "User7",
  },
  {
    _id: "8",
    views: 800,
    status: "Collecting preferences",
    requiredViews: 8000,
    public_url: "http://example.com/8",
    user: "User8",
  },
  {
    _id: "9",
    views: 900,
    status: "Success",
    requiredViews: 9000,
    public_url: "http://example.com/9",
    user: "User9",
  },
  {
    _id: "10",
    views: 1000,
    status: "Failed",
    requiredViews: 10000,
    public_url: "http://example.com/10",
    user: "User10",
  },
  {
    _id: "11",
    views: 1100,
    status: "Unreleased",
    requiredViews: 11000,
    public_url: "http://example.com/11",
    user: "User11",
  },
  {
    _id: "12",
    views: 1200,
    status: "Collecting preferences",
    requiredViews: 12000,
    public_url: "http://example.com/12",
    user: "User12",
  },
  {
    _id: "13",
    views: 1300,
    status: "Success",
    requiredViews: 13000,
    public_url: "http://example.com/13",
    user: "User13",
  },
  {
    _id: "14",
    views: 1400,
    status: "Failed",
    requiredViews: 14000,
    public_url: "http://example.com/14",
    user: "User14",
  },
]
